#!/bin/bash

# Génère un mot de passe aléatoire
generate_password() {
  local chars="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
  local password=""

  # Génère les 8 caractères aléatoires
  for i in {1..8}; do
    local random_char="${chars:RANDOM%${#chars}:1}"
    password="${password}${random_char}"
  done

  echo "${password}"
}

# Crée le dossier "data" s'il n'existe pas déjà
mkdir -p data

# Récupère le numéro de la génération en vérifiant les fichiers existants dans le dossier "data"
generation=$(ls data | grep -c "generation")

# Nom du fichier pour la nouvelle génération
filename="data/generation_n$((generation+1)).txt"

# Génère 5 mots de passe différents
for i in {1..5}; do
  # Génère le mot de passe avec le préfixe "Hexacup" et les caractères aléatoires
  password="Hexacup$(generate_password)"

  # Affiche le mot de passe généré sur une nouvelle ligne
  echo "Mot de passe généré : ${password}"

  # Ajoute le mot de passe au fichier correspondant
  echo "${password}" >> "${filename}"
done
